CREATE TABLE products(
   id               INTEGER  NOT NULL PRIMARY KEY 
  ,title            VARCHAR(21) NOT NULL
  ,category         VARCHAR(5) NOT NULL
  ,description      VARCHAR(46) NOT NULL
  ,img              VARCHAR(28) NOT NULL
  ,price            NUMERIC(5,2) NOT NULL
  ,rating           INTEGER  NOT NULL
  ,color            VARCHAR(6) NOT NULL
  ,discounted_price NUMERIC(5,2)
);
INSERT INTO products(id,title,category,description,img,price,rating,color,discounted_price) VALUES (1,'Women''s Sneakers','shoes','Comfortable and stylish women''s sneakers','womens_sneakers-min.jpg',79.99,4,'White',NULL);
INSERT INTO products(id,title,category,description,img,price,rating,color,discounted_price) VALUES (2,'Women''s High Heels','shoes','Elegant and fashionable high heels for women','womens_high_heels-min.jpg',99.99,3,'Orange',79.99);
INSERT INTO products(id,title,category,description,img,price,rating,color,discounted_price) VALUES (3,'Men''s Running Shoes','shoes','High-performance running shoes for men','mens_running_shoes-min.jpeg',89.99,5,'Blue',NULL);
INSERT INTO products(id,title,category,description,img,price,rating,color,discounted_price) VALUES (4,'Kids'' Sports Shoes','shoes','Durable sports shoes for active kids','kids_sports_shoes-min.jpg',49.99,4,'Gray',39.99);
INSERT INTO products(id,title,category,description,img,price,rating,color,discounted_price) VALUES (5,'Kids'' Sports Shoes','shoes','Durable sports shoes for active kids','kids_sports_shoes-min.jpg',49.99,4,'Gray',39.99);
INSERT INTO products(id,title,category,description,img,price,rating,color,discounted_price) VALUES (6,'Men''s Running Shoes','shoes','High-performance running shoes for men','mens_running_shoes-min.jpeg',89.99,5,'Blue',NULL);
INSERT INTO products(id,title,category,description,img,price,rating,color,discounted_price) VALUES (7,'Women''s High Heels','shoes','Elegant and fashionable high heels for women','womens_high_heels-min.jpg',99.99,3,'Orange',79.99);
INSERT INTO products(id,title,category,description,img,price,rating,color,discounted_price) VALUES (8,'Women''s Sneakers','shoes','Comfortable and stylish women''s sneakers','womens_sneakers-min.jpg',79.99,4,'White',NULL);
INSERT INTO products(id,title,category,description,img,price,rating,color,discounted_price) VALUES (9,'Women''s Sneakers','shoes','Comfortable and stylish women''s sneakers','womens_sneakers-min.jpg',79.99,4,'White',NULL);
INSERT INTO products(id,title,category,description,img,price,rating,color,discounted_price) VALUES (10,'Women''s High Heels','shoes','Elegant and fashionable high heels for women','womens_high_heels-min.jpg',99.99,3,'Orange',79.99);
INSERT INTO products(id,title,category,description,img,price,rating,color,discounted_price) VALUES (11,'Men''s Running Shoes','shoes','High-performance running shoes for men','mens_running_shoes-min.jpeg',89.99,5,'Blue',NULL);
INSERT INTO products(id,title,category,description,img,price,rating,color,discounted_price) VALUES (12,'Kids'' Sports Shoes','shoes','Durable sports shoes for active kids','kids_sports_shoes-min.jpg',49.99,4,'Gray',39.99);
INSERT INTO products(id,title,category,description,img,price,rating,color,discounted_price) VALUES (13,'Kids'' Sports Shoes','shoes','Durable sports shoes for active kids','kids_sports_shoes-min.jpg',49.99,4,'Gray',39.99);
INSERT INTO products(id,title,category,description,img,price,rating,color,discounted_price) VALUES (14,'Men''s Running Shoes','shoes','High-performance running shoes for men','mens_running_shoes-min.jpeg',89.99,5,'Blue',NULL);
INSERT INTO products(id,title,category,description,img,price,rating,color,discounted_price) VALUES (15,'Women''s High Heels','shoes','Elegant and fashionable high heels for women','womens_high_heels-min.jpg',99.99,3,'Orange',79.99);
INSERT INTO products(id,title,category,description,img,price,rating,color,discounted_price) VALUES (16,'Women''s Sneakers','shoes','Comfortable and stylish women''s sneakers','womens_sneakers-min.jpg',79.99,4,'White',NULL);
INSERT INTO products(id,title,category,description,img,price,rating,color,discounted_price) VALUES (17,'Women''s Sneakers','shoes','Comfortable and stylish women''s sneakers','womens_sneakers-min.jpg',79.99,4,'White',NULL);
INSERT INTO products(id,title,category,description,img,price,rating,color,discounted_price) VALUES (18,'Women''s High Heels','shoes','Elegant and fashionable high heels for women','womens_high_heels-min.jpg',99.99,3,'Orange',79.99);
INSERT INTO products(id,title,category,description,img,price,rating,color,discounted_price) VALUES (19,'Men''s Running Shoes','shoes','High-performance running shoes for men','mens_running_shoes-min.jpeg',89.99,5,'Blue',NULL);
INSERT INTO products(id,title,category,description,img,price,rating,color,discounted_price) VALUES (20,'Kids'' Sports Shoes','shoes','Durable sports shoes for active kids','kids_sports_shoes-min.jpg',49.99,4,'Gray',39.99);
INSERT INTO products(id,title,category,description,img,price,rating,color,discounted_price) VALUES (21,'Kids'' Sports Shoes','shoes','Durable sports shoes for active kids','kids_sports_shoes-min.jpg',49.99,4,'Gray',39.99);
INSERT INTO products(id,title,category,description,img,price,rating,color,discounted_price) VALUES (22,'Men''s Running Shoes','shoes','High-performance running shoes for men','mens_running_shoes-min.jpeg',89.99,5,'Blue',NULL);
INSERT INTO products(id,title,category,description,img,price,rating,color,discounted_price) VALUES (23,'Women''s High Heels','shoes','Elegant and fashionable high heels for women','womens_high_heels-min.jpg',99.99,3,'Orange',79.99);
INSERT INTO products(id,title,category,description,img,price,rating,color,discounted_price) VALUES (24,'Women''s Sneakers','shoes','Comfortable and stylish women''s sneakers','womens_sneakers-min.jpg',79.99,4,'White',NULL);
INSERT INTO products(id,title,category,description,img,price,rating,color,discounted_price) VALUES (25,'Women''s Sneakers','shoes','Comfortable and stylish women''s sneakers','womens_sneakers-min.jpg',79.99,4,'White',NULL);
INSERT INTO products(id,title,category,description,img,price,rating,color,discounted_price) VALUES (26,'Women''s High Heels','shoes','Elegant and fashionable high heels for women','womens_high_heels-min.jpg',99.99,3,'Orange',79.99);
INSERT INTO products(id,title,category,description,img,price,rating,color,discounted_price) VALUES (27,'Men''s Running Shoes','shoes','High-performance running shoes for men','mens_running_shoes-min.jpeg',89.99,5,'Blue',NULL);
INSERT INTO products(id,title,category,description,img,price,rating,color,discounted_price) VALUES (28,'Kids'' Sports Shoes','shoes','Durable sports shoes for active kids','kids_sports_shoes-min.jpg',49.99,4,'Gray',39.99);
INSERT INTO products(id,title,category,description,img,price,rating,color,discounted_price) VALUES (29,'Kids'' Sports Shoes','shoes','Durable sports shoes for active kids','kids_sports_shoes-min.jpg',49.99,4,'Gray',39.99);
INSERT INTO products(id,title,category,description,img,price,rating,color,discounted_price) VALUES (30,'Men''s Running Shoes','shoes','High-performance running shoes for men','mens_running_shoes-min.jpeg',89.99,5,'Blue',NULL);
INSERT INTO products(id,title,category,description,img,price,rating,color,discounted_price) VALUES (31,'Women''s High Heels','shoes','Elegant and fashionable high heels for women','womens_high_heels-min.jpg',99.99,3,'Orange',79.99);
INSERT INTO products(id,title,category,description,img,price,rating,color,discounted_price) VALUES (32,'Women''s Sneakers','shoes','Comfortable and stylish women''s sneakers','womens_sneakers-min.jpg',79.99,4,'White',NULL);
INSERT INTO products(id,title,category,description,img,price,rating,color,discounted_price) VALUES (33,'Women''s Shoulder Bag','bags','Stylish and spacious shoulder bag for women','womens_shoulder_bag-min.jpg',59.99,2,'White',39.99);
INSERT INTO products(id,title,category,description,img,price,rating,color,discounted_price) VALUES (34,'Men''s Backpack','bags','Versatile and sturdy backpack for men','mens_backpack-min.jpg',69.99,4,'Gray',NULL);
INSERT INTO products(id,title,category,description,img,price,rating,color,discounted_price) VALUES (35,'Kids'' School Backpack','bags','Durable and practical school backpack for kids','kids_school_backpack-min.jpg',39.99,3,'Blue',24.99);
INSERT INTO products(id,title,category,description,img,price,rating,color,discounted_price) VALUES (36,'Women''s Clutch Purse','bags','Elegant and compact clutch purse for women','womens_clutch_purse-min.jpg',39.99,5,'Yellow',NULL);
INSERT INTO products(id,title,category,description,img,price,rating,color,discounted_price) VALUES (37,'Women''s Clutch Purse','bags','Elegant and compact clutch purse for women','womens_clutch_purse-min.jpg',39.99,5,'Yellow',NULL);
INSERT INTO products(id,title,category,description,img,price,rating,color,discounted_price) VALUES (38,'Kids'' School Backpack','bags','Durable and practical school backpack for kids','kids_school_backpack-min.jpg',39.99,3,'Blue',24.99);
INSERT INTO products(id,title,category,description,img,price,rating,color,discounted_price) VALUES (39,'Men''s Backpack','bags','Versatile and sturdy backpack for men','mens_backpack-min.jpg',69.99,4,'Gray',NULL);
INSERT INTO products(id,title,category,description,img,price,rating,color,discounted_price) VALUES (40,'Women''s Shoulder Bag','bags','Stylish and spacious shoulder bag for women','womens_shoulder_bag-min.jpg',59.99,2,'White',39.99);
INSERT INTO products(id,title,category,description,img,price,rating,color,discounted_price) VALUES (41,'Women''s Shoulder Bag','bags','Stylish and spacious shoulder bag for women','womens_shoulder_bag-min.jpg',59.99,2,'White',39.99);
INSERT INTO products(id,title,category,description,img,price,rating,color,discounted_price) VALUES (42,'Men''s Backpack','bags','Versatile and sturdy backpack for men','mens_backpack-min.jpg',69.99,4,'Gray',NULL);
INSERT INTO products(id,title,category,description,img,price,rating,color,discounted_price) VALUES (43,'Kids'' School Backpack','bags','Durable and practical school backpack for kids','kids_school_backpack-min.jpg',39.99,3,'Blue',24.99);
INSERT INTO products(id,title,category,description,img,price,rating,color,discounted_price) VALUES (44,'Women''s Clutch Purse','bags','Elegant and compact clutch purse for women','womens_clutch_purse-min.jpg',39.99,5,'Yellow',NULL);
INSERT INTO products(id,title,category,description,img,price,rating,color,discounted_price) VALUES (45,'Women''s Clutch Purse','bags','Elegant and compact clutch purse for women','womens_clutch_purse-min.jpg',39.99,5,'Yellow',NULL);
INSERT INTO products(id,title,category,description,img,price,rating,color,discounted_price) VALUES (46,'Kids'' School Backpack','bags','Durable and practical school backpack for kids','kids_school_backpack-min.jpg',39.99,3,'Blue',24.99);
INSERT INTO products(id,title,category,description,img,price,rating,color,discounted_price) VALUES (47,'Men''s Backpack','bags','Versatile and sturdy backpack for men','mens_backpack-min.jpg',69.99,4,'Gray',NULL);
INSERT INTO products(id,title,category,description,img,price,rating,color,discounted_price) VALUES (48,'Women''s Shoulder Bag','bags','Stylish and spacious shoulder bag for women','womens_shoulder_bag-min.jpg',59.99,2,'White',39.99);
INSERT INTO products(id,title,category,description,img,price,rating,color,discounted_price) VALUES (49,'Women''s Shoulder Bag','bags','Stylish and spacious shoulder bag for women','womens_shoulder_bag-min.jpg',59.99,2,'White',39.99);
INSERT INTO products(id,title,category,description,img,price,rating,color,discounted_price) VALUES (50,'Men''s Backpack','bags','Versatile and sturdy backpack for men','mens_backpack-min.jpg',69.99,4,'Gray',NULL);
INSERT INTO products(id,title,category,description,img,price,rating,color,discounted_price) VALUES (51,'Kids'' School Backpack','bags','Durable and practical school backpack for kids','kids_school_backpack-min.jpg',39.99,3,'Blue',24.99);
INSERT INTO products(id,title,category,description,img,price,rating,color,discounted_price) VALUES (52,'Women''s Clutch Purse','bags','Elegant and compact clutch purse for women','womens_clutch_purse-min.jpg',39.99,5,'Yellow',NULL);
INSERT INTO products(id,title,category,description,img,price,rating,color,discounted_price) VALUES (53,'Women''s Clutch Purse','bags','Elegant and compact clutch purse for women','womens_clutch_purse-min.jpg',39.99,5,'Yellow',NULL);
INSERT INTO products(id,title,category,description,img,price,rating,color,discounted_price) VALUES (54,'Kids'' School Backpack','bags','Durable and practical school backpack for kids','kids_school_backpack-min.jpg',39.99,3,'Blue',24.99);
INSERT INTO products(id,title,category,description,img,price,rating,color,discounted_price) VALUES (55,'Men''s Backpack','bags','Versatile and sturdy backpack for men','mens_backpack-min.jpg',69.99,4,'Gray',NULL);
INSERT INTO products(id,title,category,description,img,price,rating,color,discounted_price) VALUES (56,'Women''s Shoulder Bag','bags','Stylish and spacious shoulder bag for women','womens_shoulder_bag-min.jpg',59.99,2,'White',39.99);
INSERT INTO products(id,title,category,description,img,price,rating,color,discounted_price) VALUES (57,'Women''s Shoulder Bag','bags','Stylish and spacious shoulder bag for women','womens_shoulder_bag-min.jpg',59.99,2,'White',39.99);
INSERT INTO products(id,title,category,description,img,price,rating,color,discounted_price) VALUES (58,'Men''s Backpack','bags','Versatile and sturdy backpack for men','mens_backpack-min.jpg',69.99,4,'Gray',NULL);
INSERT INTO products(id,title,category,description,img,price,rating,color,discounted_price) VALUES (59,'Kids'' School Backpack','bags','Durable and practical school backpack for kids','kids_school_backpack-min.jpg',39.99,3,'Blue',24.99);
INSERT INTO products(id,title,category,description,img,price,rating,color,discounted_price) VALUES (60,'Women''s Clutch Purse','bags','Elegant and compact clutch purse for women','womens_clutch_purse-min.jpg',39.99,5,'Yellow',NULL);
INSERT INTO products(id,title,category,description,img,price,rating,color,discounted_price) VALUES (61,'Women''s Clutch Purse','bags','Elegant and compact clutch purse for women','womens_clutch_purse-min.jpg',39.99,5,'Yellow',NULL);
INSERT INTO products(id,title,category,description,img,price,rating,color,discounted_price) VALUES (62,'Kids'' School Backpack','bags','Durable and practical school backpack for kids','kids_school_backpack-min.jpg',39.99,3,'Blue',24.99);
INSERT INTO products(id,title,category,description,img,price,rating,color,discounted_price) VALUES (63,'Men''s Backpack','bags','Versatile and sturdy backpack for men','mens_backpack-min.jpg',69.99,4,'Gray',NULL);
INSERT INTO products(id,title,category,description,img,price,rating,color,discounted_price) VALUES (64,'Women''s Shoulder Bag','bags','Stylish and spacious shoulder bag for women','womens_shoulder_bag-min.jpg',59.99,2,'White',39.99);
INSERT INTO products(id,title,category,description,img,price,rating,color,discounted_price) VALUES (65,'Women''s Brim Hat','hats','Stylish and elegant wide-brim hat for women','wide_brim_hat_women-min.jpg',29.99,1,'Beige',24.99);
INSERT INTO products(id,title,category,description,img,price,rating,color,discounted_price) VALUES (66,'Men''s Fedora Hat','hats','Classic and timeless fedora hat for men','fedora_hat_men-min.jpg',39.99,3,'Brown',34.99);
INSERT INTO products(id,title,category,description,img,price,rating,color,discounted_price) VALUES (67,'Women''s Beanie Hat','hats','Warm and cozy beanie hat for women','beanie_hat_women-min.jpg',19.99,5,'Gray',NULL);
INSERT INTO products(id,title,category,description,img,price,rating,color,discounted_price) VALUES (68,'Men''s Baseball Cap','hats','Casual and comfortable baseball cap for men','baseball_cap_men-min.jpg',24.99,4,'Gray',NULL);
INSERT INTO products(id,title,category,description,img,price,rating,color,discounted_price) VALUES (69,'Men''s Baseball Cap','hats','Casual and comfortable baseball cap for men','baseball_cap_men-min.jpg',24.99,4,'Gray',NULL);
INSERT INTO products(id,title,category,description,img,price,rating,color,discounted_price) VALUES (70,'Women''s Beanie Hat','hats','Warm and cozy beanie hat for women','beanie_hat_women-min.jpg',19.99,5,'Gray',NULL);
INSERT INTO products(id,title,category,description,img,price,rating,color,discounted_price) VALUES (71,'Men''s Fedora Hat','hats','Classic and timeless fedora hat for men','fedora_hat_men-min.jpg',39.99,3,'Brown',34.99);
INSERT INTO products(id,title,category,description,img,price,rating,color,discounted_price) VALUES (72,'Women''s Brim Hat','hats','Stylish and elegant wide-brim hat for women','wide_brim_hat_women-min.jpg',29.99,1,'Beige',24.99);
INSERT INTO products(id,title,category,description,img,price,rating,color,discounted_price) VALUES (73,'Women''s Brim Hat','hats','Stylish and elegant wide-brim hat for women','wide_brim_hat_women-min.jpg',29.99,1,'Beige',24.99);
INSERT INTO products(id,title,category,description,img,price,rating,color,discounted_price) VALUES (74,'Men''s Fedora Hat','hats','Classic and timeless fedora hat for men','fedora_hat_men-min.jpg',39.99,3,'Brown',34.99);
INSERT INTO products(id,title,category,description,img,price,rating,color,discounted_price) VALUES (75,'Women''s Beanie Hat','hats','Warm and cozy beanie hat for women','beanie_hat_women-min.jpg',19.99,5,'Gray',NULL);
INSERT INTO products(id,title,category,description,img,price,rating,color,discounted_price) VALUES (76,'Men''s Baseball Cap','hats','Casual and comfortable baseball cap for men','baseball_cap_men-min.jpg',24.99,4,'Gray',NULL);
INSERT INTO products(id,title,category,description,img,price,rating,color,discounted_price) VALUES (77,'Men''s Baseball Cap','hats','Casual and comfortable baseball cap for men','baseball_cap_men-min.jpg',24.99,4,'Gray',NULL);
INSERT INTO products(id,title,category,description,img,price,rating,color,discounted_price) VALUES (78,'Women''s Beanie Hat','hats','Warm and cozy beanie hat for women','beanie_hat_women-min.jpg',19.99,5,'Gray',NULL);
INSERT INTO products(id,title,category,description,img,price,rating,color,discounted_price) VALUES (79,'Men''s Fedora Hat','hats','Classic and timeless fedora hat for men','fedora_hat_men-min.jpg',39.99,3,'Brown',34.99);
INSERT INTO products(id,title,category,description,img,price,rating,color,discounted_price) VALUES (80,'Women''s Brim Hat','hats','Stylish and elegant wide-brim hat for women','wide_brim_hat_women-min.jpg',29.99,1,'Beige',24.99);
INSERT INTO products(id,title,category,description,img,price,rating,color,discounted_price) VALUES (81,'Women''s Brim Hat','hats','Stylish and elegant wide-brim hat for women','wide_brim_hat_women-min.jpg',29.99,1,'Beige',24.99);
INSERT INTO products(id,title,category,description,img,price,rating,color,discounted_price) VALUES (82,'Men''s Fedora Hat','hats','Classic and timeless fedora hat for men','fedora_hat_men-min.jpg',39.99,3,'Brown',34.99);
INSERT INTO products(id,title,category,description,img,price,rating,color,discounted_price) VALUES (83,'Women''s Beanie Hat','hats','Warm and cozy beanie hat for women','beanie_hat_women-min.jpg',19.99,5,'Gray',NULL);
INSERT INTO products(id,title,category,description,img,price,rating,color,discounted_price) VALUES (84,'Men''s Baseball Cap','hats','Casual and comfortable baseball cap for men','baseball_cap_men-min.jpg',24.99,4,'Gray',NULL);
INSERT INTO products(id,title,category,description,img,price,rating,color,discounted_price) VALUES (85,'Men''s Baseball Cap','hats','Casual and comfortable baseball cap for men','baseball_cap_men-min.jpg',24.99,4,'Gray',NULL);
INSERT INTO products(id,title,category,description,img,price,rating,color,discounted_price) VALUES (86,'Women''s Beanie Hat','hats','Warm and cozy beanie hat for women','beanie_hat_women-min.jpg',19.99,5,'Gray',NULL);
INSERT INTO products(id,title,category,description,img,price,rating,color,discounted_price) VALUES (87,'Men''s Fedora Hat','hats','Classic and timeless fedora hat for men','fedora_hat_men-min.jpg',39.99,3,'Brown',34.99);
INSERT INTO products(id,title,category,description,img,price,rating,color,discounted_price) VALUES (88,'Women''s Brim Hat','hats','Stylish and elegant wide-brim hat for women','wide_brim_hat_women-min.jpg',29.99,1,'Beige',24.99);
INSERT INTO products(id,title,category,description,img,price,rating,color,discounted_price) VALUES (89,'Women''s Brim Hat','hats','Stylish and elegant wide-brim hat for women','wide_brim_hat_women-min.jpg',29.99,1,'Beige',24.99);
INSERT INTO products(id,title,category,description,img,price,rating,color,discounted_price) VALUES (90,'Men''s Fedora Hat','hats','Classic and timeless fedora hat for men','fedora_hat_men-min.jpg',39.99,3,'Brown',34.99);
INSERT INTO products(id,title,category,description,img,price,rating,color,discounted_price) VALUES (91,'Women''s Beanie Hat','hats','Warm and cozy beanie hat for women','beanie_hat_women-min.jpg',19.99,5,'Gray',NULL);
INSERT INTO products(id,title,category,description,img,price,rating,color,discounted_price) VALUES (92,'Men''s Baseball Cap','hats','Casual and comfortable baseball cap for men','baseball_cap_men-min.jpg',24.99,4,'Gray',NULL);
INSERT INTO products(id,title,category,description,img,price,rating,color,discounted_price) VALUES (93,'Men''s Baseball Cap','hats','Casual and comfortable baseball cap for men','baseball_cap_men-min.jpg',24.99,4,'Gray',NULL);
INSERT INTO products(id,title,category,description,img,price,rating,color,discounted_price) VALUES (94,'Women''s Beanie Hat','hats','Warm and cozy beanie hat for women','beanie_hat_women-min.jpg',19.99,5,'Gray',NULL);
INSERT INTO products(id,title,category,description,img,price,rating,color,discounted_price) VALUES (95,'Men''s Fedora Hat','hats','Classic and timeless fedora hat for men','fedora_hat_men-min.jpg',39.99,3,'Brown',34.99);
INSERT INTO products(id,title,category,description,img,price,rating,color,discounted_price) VALUES (96,'Women''s Brim Hat','hats','Stylish and elegant wide-brim hat for women','wide_brim_hat_women-min.jpg',29.99,1,'Beige',24.99);
